### ISSUE TITLE
gimp integration is now available through gmic

### ISSUE THREAD

**Issue by spaskalev** [mjambon/purple-fringe#1]
Just a heads up, I ported the unpurple as a g'mic filter and it is now available through the gmic plugin in gimp, krita and paint.net. See https://github.com/dtschump/gmic-community/pull/241

Regards,
Stanislav

**Comment by mjambon** [comment]
This is fantastic. I'm honored. Thank you.

**Comment by spaskalev** [comment]
Thanks for the algorithm.

Since it is a port and not a direct binary or source reuse I didn't know what license to set, so I put a public domain label on top. Let me know if you want another license on it and/or a copyright in your name - I don't mind at all, I'm just a happy user of it :)

**Comment by mjambon** [comment]
You're the author of the code, so there's no copyright issue. However, may I ask you to insert my name in the description near the URL, since it may break at some point in the future? Thanks!

**Comment by spaskalev** [comment]
Gladly, I've posted https://github.com/dtschump/gmic-community/pull/242

**Comment by mjambon** [comment]
Thank you!
